#! /bin/bash
################################################################################
#
#  vmmaestro - Tiny KVM wrapper
#
#  Copyright (C) 2014-2018 Koichi MATSUMOTO.  All rights reserved.
#
################################################################################

#E=echo

########################################
# use_sudo : y use sudo command 
#            d use doas command
#            else not use any commnad
########################################
use_sudo='y'

########################################
#### System
########################################

SYSDIR='/etc/vmmaestro'
DEF_NIC='virtio'
DEF_DISKIF='virtio'

boot_qemu_delay=10

########################################
#### Preset Default values
########################################
function set_default_values
{
  user_runas='kvm'
  cpu_model='host'
  cpu_units=1
  cpu_iswinguest=0
  memory_vmem=1024
  display_type='vnc'
  graphics_type='std'
  vnc_addr='127.0.0.1'
  spice_addr='127.0.0.1'
  vnc_number='0'
  spice_tls='n'
  spice_sasl='n'
  clock_utctime='y'
  clock_sync_host='y'
  cdrom_if='ide'
  disk_num=0
}

########################################
#### check args
########################################

if [[ $# < 2 ]]; then
  case "$1" in
    list)
      ;;
    *)
      echo 'VmMaestro - Tiny shell script for KVM control'
      echo
      echo -e '       '$0' start vm ...                  :Start VM'
      echo -e '       '$0' consolestart|cstart vm ...    :Start VM with serial console'
      echo -e '       '$0' shutdown vm ...               :Shutdown VM'
      echo -e '       '$0' stop vm ...                   :Stop VM (without shutodnw)'
      echo -e '       '$0' restart vm ...                :Restart VM'
      echo -e '       '$0' kill vm ...                   :Kill VM'
      echo -e '       '$0' console|serial|serial0 vm ... :Enter serial console of VM'
      echo -e '       '$0' monitor|kvm|qemu vm ...       :Enter KVM monitor of VM'
      echo -e '       '$0' status vm ...                 :Show VM running status'
      echo -e '       '$0' show vm ...                   :Show VM details'
      echo -e '       '$0' list [-s|--status]            :List VM details or status'
      echo
      exit 1
      ;;
  esac
fi

########################################
#### create startup command line
########################################
##############################
#### is enabled IOMMU
##############################
function io_mmu
{
  vendor=`grep vendor_id /proc/cpuinfo | uniq | awk '{ print $3; }'`
  iommu_args=''
  iommu_vendor=''
  sudo dmesg | grep -e 'IOMMU enabled' > /dev/null
  if [[ $? == 0 ]]; then
    if [[ $vendor == 'GenuineIntel' ]]; then
      iommu_args='-device intel-iommu'
      iommu_vendor='Intel'
    else
      iommu_args='-device amd-iommu'
      iommu_vendor='AMD'
    fi
  else
    iommu_args=''
  fi
}

##############################
#### check CPU
##############################
function check_cpu
{
  target_cpu=$1
  TMPFILE=/tmp/.vmmaestro.tmp
  $system_qemu -cpu ? > $TMPFILE 2>&1
  CPUs=$(awk "/^x86/{ print $2; }" $TMPFILE)
  for c in $CPUs
  do
    if [[ $target_cpu = $c ]]; then
      return 1
    fi
  done

  return 0
}

##############################
#### create CPU
##############################
function create_cpu
{
  check_cpu $cpu_model
  if [[ ! $? ]]; then
    echo "Illegal cpu model = "$cpu_model
    exit 2
  fi

  cpu_args='-cpu '$cpu_model' -smp '$cpu_units
  
  if [[ x$cpu_cores != x ]]; then
    cpu_args=$cpu_args',cores='$cpu_cores
  fi
  if [[ x$cpu_threads != x ]]; then
    cpu_args=$cpu_args',threads='$cpu_threads
  fi
  if [[ x$cpu_sockets != x ]]; then
    cpu_args=$cpu_args',sockets='$cpu_sockets
  fi
  if [[ $cpu_iswinguest != 0 ]]; then
    cpu_args=$cpu_args',hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time'
  fi
}

##############################
#### check NUMA
##############################
function check_numa
{
  if [[ $numa_is_numa == 'y' ]]; then
    numa_args='-numa '$numa_numa_opts
    if [[ $memory_huge == 'y' && $memory_share == 'y' ]]; then
      numa_args=$numa_args',memdev=mem'
    fi
  else
    numa_args=''
  fi 
}

##############################
#### create rng
##############################
function create_rng
{
  rng_args=''
  if [[ $rng_enable == 'y' ]]; then
    rng_args='-object rng-random,filename=/dev/hwrng,id=rng0 '
    rng_args=$rng_args'-device virtio-rng-pci,rng=rng0'
  fi
}

##############################
#### create Memory
##############################
function create_mem
{
  mem_args='-m '$memory_vmem
  if [[ $memory_auto == 'y' ]]; then
    mem_args=$mem_args' -device virtio-balloon,automatic=true'
  else
    mem_args=$mem_args' -device virtio-balloon'
  fi
  if [[ $memory_huge == 'y' ]]; then
    if [[ $memory_share == 'y' ]]; then
      if  [[ ! $memory_sharemem ]]; then
        memory_sharemem=$memory_vmem
      fi
      mem_args=$mem_args' -object memory-backend-file,id=mem,size='${memory_sharemem}'M,mem-path=/dev/hugepages,share=on'
    else
      mem_args=$mem_args' -mem-path /dev/hugepages'
    fi
    if [[ $memory_prealloc == 'y' ]]; then
      mem_args=$memargs' -mem-prealloc'
    fi
  fi
}

##############################
#### creete bios args
##############################
function create_bios
{
  bios_args=''
  if [[ x$bios_file != x ]]; then
    bios_args='-smbios file='$bios_file
  fi
  case  "$bios_type" in
    'uefi')
      if [[ x$bios_file != x ]]; then
        if [[ x$bios_nvram != x ]]; then
          bios_args='-drive if=pflash,unit=0,format=raw,readonly,file='$bios_file
          bios_args=$bios_args' -drive if=pflash,unit=1,format=raw,file='$bios_nvram
        else
          bios_args='-drive if=pflash,format=raw,file='$bios_file
        fi
      else
        echo "Missing UEFI file."
        exit 3
      fi
      ;;
    '0')
      bios_args=$bios_args' -smbios type=0'
      if [[ x$bios_vendor != x ]]; then
        bios_args=$bios_args',vender='$bios_vendor
      fi
      if [[ x$bios_version != x ]]; then
        bios_args=$bios_args',version='$bios_version
      fi
      if [[ x$bios_date != x ]]; then
        bios_args=$bios_args',date='$bios_date
      fi
      if [[ x$bios_release != x ]]; then
        bios_args=$bios_args',release'$bios_release
      fi
      ;;
    '1')
      bios_args=$bios_args' -smbios type=1'
      if [[ x$bios_manufacturer != x ]]; then
        bios_args=$bios_args',manufacturer='$bios_manufacturer
      fi
      if [[ x$bios_product != x ]]; then
        bios_args=$bios_args',product='$bios_product
      fi
      if [[ x$bios_version != x ]]; then
        bios_args=$bios_args',version='$bios_version
      fi
      if [[ x$bios_serial != x ]]; then
        bios_args=$bios_args',serial='$bios_serial
      fi
      if [[ x$bios_uuid != x ]]; then
        bios_args=$bios_args',uuid='$bios_uuid
      fi
      if [[ x$bios_sku != x ]]; then
        bios_args=$bios_args',sku='$bios_sku
      fi
      if [[ x$bios_family != x ]]; then
        bios_args=$bios_args',family='$bios_family
      fi
      ;;
    '2')
      bios_args=$bios_args' -smbios type=2'
      if [[ x$bios_manufacturer != x ]]; then
        bios_args=$bios_args',manufacturer='$bios_manufacturer
      fi
      if [[ x$bios_product != x ]]; then
        bios_args=$bios_args',product='$bios_product
      fi
      if [[ x$bios_version != x ]]; then
        bios_args=$bios_args',version='$bios_version
      fi
      if [[ x$bios_serial != x ]]; then
        bios_args=$bios_args',serial='$bios_serial
      fi
      if [[ x$bios_asset != x ]]; then
        bios_args=$bios_args',asset='$bios_asset
      fi
      if [[ x$bios_location != x ]]; then
        bios_args=$bios_args',location='$bios_location
      fi
      if [[ x$bios_family != x ]]; then
        bios_args=$bios_args',family='$bios_family
      fi
      ;;
    '3')
      bios_args=$bios_args' -smbios type=3'
      if [[ x$bios_manufacturer != x ]]; then
        bios_args=$bios_args',manufacturer='$bios_manufacturer
      fi
      if [[ x$bios_version != x ]]; then
        bios_args=$bios_args',version='$bios_version
      fi
      if [[ x$bios_serial != x ]]; then
        bios_args=$bios_args',serial='$bios_serial
      fi
      if [[ x$bios_asset != x ]]; then
        bios_args=$bios_args',asset='$bios_asset
      fi
      if [[ x$bios_sku != x ]]; then
        bios_args=$bios_args',sku='$bios_sku
      fi
      ;;
    '4')
      bios_args=$bios_args' -smbios type=4'
      if [[ x$bios_sock != x ]]; then
        bios_args=$bios_args',sock_pfx='$bios_sock
      fi
      if [[ x$bios_manufacturer != x ]]; then
        bios_args=$bios_args',manufacturer='$bios_manufacturer
      fi
      if [[ x$bios_version != x ]]; then
        bios_args=$bios_args',version='$bios_version
      fi
      if [[ x$bios_serial != x ]]; then
        bios_args=$bios_args',serial='$bios_serial
      fi
      if [[ x$bios_asset != x ]]; then
        bios_args=$bios_args',asset='$bios_asset
      fi
      if [[ x$bios_part != x ]]; then
        bios_args=$bios_args',part='$bios_part
      fi
      ;;
    '17')
      bios_args=$bios_args' -smbios type=17'
      if [[ x$bios_loc_pfx != x ]]; then
        bios_args=$bios_args',loc_pfx='$bios_loc_pfx
      fi
      if [[ x$bios_bank != x ]]; then
        bios_args=$bios_args',bank='$bios_bank
      fi
      if [[ x$bios_manufacturer != x ]]; then
        bios_args=$bios_args',manufacturer='$bios_manufacturer
      fi
      if [[ x$bios_serial != x ]]; then
        bios_args=$bios_args',serial='$bios_serial
      fi
      if [[ x$bios_asset != x ]]; then
        bios_args=$bios_args',asset='$bios_asset
      fi
      if [[ x$bios_part != x ]]; then
        bios_args=$bios_args',part='$bios_part
      fi
      if [[ x$bios_speed != x ]]; then
        bios_args=$bios_args',speed='$bios_speed
      fi
      ;;
    '*')
      ;;
  esac
}

##############################
### create TPM device
##############################
function create_tpm
{
  tpm_args=""
  if [[ x"${tpm_enable}" = x"true" || x"${tpm_enable}" = x"yes" ]]; then
    if [[ x"${tpm_type}" = x"passthrough" ]]; then
      tpm_args="-tpmdev passthrough, id="${tpm_id}",path="${tpm_dev}" "
      tpm_args=$tpm_args"-device tpm-tis,tpmdev="${tpm_id}
    elif [[ x"${tpm_type}" = x"emulator" ]]; then
      tpm_args="-chardev socket,id="${tpm_char_id}",path="${tpm_char_path}" "
      tpm_args=$tpm_args"-tpmdev emulator,id="${tpm_id}",chardev="${tpm_char_id}
      tpm_args=$tpm_args"-device tpm-tis,tpmdev="${tpm_id}
    else
      echo "Illegal TPM type: "${tpm_type}
      exit 28
    fi
  fi
}

##############################
#### creete drive args
##############################
function create_disk_drive
{
  disk_args=""
  idx=0
  while [[ x${disk_lv[$idx]} != x ]];
  do
    if [[ x$vg_name != x ]]; then
        disk_drive=/dev/$vg_name/${disk_lv[$idx]}
        if [[ ! -b $disk_drive ]]; then
            echo "Specified block device does not exist: "$disk_drive
            exit 4
        fi
    else
        disk_drive=${disk_lv[$idx]}
        if [[ ! -f $disk_drive ]]; then
            echo "Specified disk file does not exist: "$disk_drive
            exit 5
        fi
    fi
    if [[ x${disk_if[$idx]} == x ]]; then
      disk_if[$idx]=$DEF_DISKIF
    fi
    case "${disk_if[$idx]}" in
      "ide")      ;;
      "scsi")     ;;
      "virtio")   ;;
      "virtio-scsi") ;;
      *)
        echo "Unknown disk interface: "${disk_if[$idx]}
        exit 6
        ;;
    esac
    if [[ ${disk_if[$idx]} == 'virtio' || ${disk_if[$idx]} == 'virtio-scsi' ]]; then
      drive_id='drive'$idx
      disk_args=$disk_args' -drive if=none,id='$drive_id
      disk_args=$disk_args',aio=native,cache.direct=on,format=raw,file='$disk_drive
      disk_args=$disk_args',index='$idx',media=disk'
      if [[ ${disk_if[$idx]} == 'virtio-scsi' ]]; then
        disk_args=$disk_args' -device virtio-scsi,drive='$drive_id
        disk_args=$disk_args',scsi=on,config-wce=off'
      else
        disk_args=$disk_args' -device virtio-blk,drive='$drive_id
        disk_args=$disk_args',scsi=off,config-wce=off'
      fi
    else
      if [[ x${disk_aio[$idx]} == x ]]; then
        disk_aio[$idx]='native'
      fi
      case "${disk_aio[$idx]}" in
        "native")   ;;
        "threads")  ;;
        *)
          echo "Unknown AIO type: "${disk_aio[$idx]}
          exit 7
          ;;
      esac
      disk_args=$disk_args' -drive if='${disk_if[$idx]}',aio='${disk_aio[$idx]}',cache.direct=on'
      if [[ x${disk_fmt[$idx]} != x ]]; then
        disk_args=$disk_args',format='${disk_fmt[$idx]}
      fi
      disk_args=$disk_args',file='$disk_drive
      disk_args=$disk_args',index='$idx',media=disk'
    fi
    ((idx=idx+1))
  done
  disk_num=$idx
}

##############################
#### creete floppy disk
##############################
function create_floppy
{
  fd_args=""
  if [[ x$floppy_drive1 != x ]]; then
    fd_file=$floppy_drive1
    if [[ ! -f $floppy_drive1 ]]; then
        echo "Specified floppy file does not exist: "$floppy_drive1
        exit 8
    fi
    fd_args=$fd_args' -drive file='$floppy_drive1',if=floppy,index=0'
  fi
  if [[ x$floppy_drive2 != x ]]; then
    fd_file=$floppy_drive2
    if [[ ! -f $floppy_drive2 ]]; then
        echo "Specified floppy file does not exist: "$floppy_drive2
        exit 9
    fi
    fd_args=$fd_args' -drive file='$floppy_drive2',if=floppy,index=1'
  fi
}

##############################
#### CD-ROM
##############################
function create_cdrom {
  cd_args=""
  case "$cdrom_if" in
    "ide")    ;;
    "scsi")   ;;
     *)
       echo "Unknown CD Interface: "$cdrom_if
  esac
  cd_args=$cd_args' -drive if='$cdrom_if',aio=native'
  if [[ x$cdrom_iso != x ]]; then
    if [[ ! -f $cdrom_iso ]]; then
        echo "Specified iso file does not exist."
        exit 10
    fi
    cd_args=$cd_args',cache.direct=on,file='$cdrom_iso
  fi
  cd_args=$cd_args',index='$disk_num',media=cdrom'
}

##############################
### VirtFS
##############################
function create_virtfs
{
  if [[ $virtfs_enable == 'y' ]] ; then
    virtfs_args=''
    case "$virtfs_driver" in
      "local")	;;
      "handle")	;;
      "proxy")	;;
      *)
        echo "Illegal FsDriver: "$virtfs_driver
        exit 11
        ;;
    esac
    virtfs_args='-virtfs fsdriver='$virtfs_driver
    if [[ x$virtfs_id == x ]]; then
      virtfs_id=$vm
    fi
    virtfs_args=$virtfs_args",id="$virtfs_id
    if [[ ! -d $virtfs_path ]]; then
      echo "Directory does not exist! "$virtfs_path
      exit 12
    fi
    virtfs_args=$virtfs_args",path="$virtfs_path
    if [[ x$virtfs_security != x ]] ; then
      case "$virtfs_security" in
        "passthrough")	;;
        "mapped-xattr")	;;
        "mapped-file")	;;
        "none")	;;
        *)
          echo "Illegal secirity mode!"
          exit 13
          ;;
      esac
      virtfs_args=$virtfs_args",security_model="$virtfs_security
      if [[ $virtfs_writeout == 'y' ]]; then
          virtfs_args=$virtfs_args",writeout=immediate"
      fi
      if [[ $virtfs_readonly == 'y' ]]; then
        virtfs_args=$virtfs_args",readonly"
      fi
      if [[ $virtfs_driver == "proxy" ]]; then
        virtfs_args=$virtfs_args",socket="$system_rundir/$vm/virtfs.sock
        virtfs_args=$virtfs_args",sock_fd"
      fi
    fi
  fi
}

##############################
### Boot order
##############################
function create_bootorder
{
  boot_args=""
  if [[ x$boot_order != x ]]; then
    boot_args='-boot '$boot_order
    if [[ x$bios_menu == 'y' ]]; then
      boot_args=$boot_args",menu=on"
    fi
  else
    if [[ x$bios_menu == 'y' ]]; then
      boot_args="-boot menu=on"
    fi
  fi
}

##############################
#### Nic model
##############################
function check_nic
{
  model=$1
  nic_models="virtio i82551 i82557b i82559er ne2k_pci ne2k_isa pcnet"
  nic_models=$nic_models" rtl8139 e1000 smc91c111 lance mcf_fec"
  for m in $nic_models
  do
    if [[ $m == $model ]]; then
      return 1
    fi
  done

  return 0
}

##############################
#### Mac address
##############################
function create_macaddr
{
  macaddr=''
  if [[ ${network_addr[$idx]} == 'random' ]]; then
    macaddr=`printf "00:16:3E:%02X:%02X:%02X" $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff )) $(( $RANDOM & 0xff))`
  else
    macaddr=${network_addr[$idx]}
  fi
}

##############################
#### Network
##############################
function create_network_adaptor
{
  net_args=""
  idx=0
  while [[ x${network_type[$idx]} != x ]];
  do

    nic_arg=""
    
    if [[ x${network_name[$idx]} == x ]]; then
      echo "Need NIC symbol name: "$idx
      exit 14
    fi
    if [[ x${network_model[$idx]} == x ]]; then
      network_model[$idx]=$DEF_NIC
    fi
    check_nic ${network_model[$idx]}
    if [[ ! $? ]]; then
      echo "Illegal nic model: "$${network_model[$idx]} 
      exit 15
    fi

    case "${network_type[$idx]}" in
      "bridge")
        nic_arg='-netdev '${network_type[$idx]}',id='${network_name[$idx]}
        nic_arg=$nic_arg',br='${network_bridge[$idx]}
        nic_arg=$nic_arg' -net nic'
        if [[ ${network_vlan[$idx]} ]]; then
          nic_arg=$nic_arg',vlan='$network_vlan
        fi
        if [[ ${network_addr[$idx]} ]]; then
          create_macaddr
          nic_arg=$nic_arg',macaddr='${macaddr}
        fi
        nic_arg=$nic_arg',model='${network_model[$idx]}
        nic_arg=$nic_arg',netdev='${network_name[$idx]}
        ;;
      "tap")
        nic_arg='-netdev '${network_type[$idx]}',id='${network_name[$idx]}
        if [[ x${network_vhost[$idx]} != x && ${network_vhost[$idx]} == 'y' ]]; then
          nic_arg=$nic_arg',vhost=on'
          network_model[$idx]=$DEF_NIC
        fi
        if [[ x${network_if[$idx]} == x ]]; then
          echo "Need NIC interface name: "$idx
          exit 16
        fi
        nic_arg=$nic_arg',ifname='${network_if[$idx]}
        if [[ x${network_ifup[$idx]} == x ]]; then
          nic_arg=$nic_arg',script=no'
        else
          nic_arg=$nic_arg',script='${network_ifup[$idx]}
        fi
        if [[ x${network_ifdown[$idx]} != x ]]; then
          nic_arg=$nic_arg',downscript='${network_ifdown[$idx]}
        fi
        nic_arg=$nic_arg' -net nic'
        if [[ ${network_vlan[$idx]} ]]; then
          nic_arg=$nic_arg',vlan='$network_vlan
        fi
        if [[ ${network_addr[$idx]} ]]; then
          create_macaddr
          nic_arg=$nic_arg',macaddr='${macaddr}
        fi
        nic_arg=$nic_arg',model='${network_model[$idx]}
        nic_arg=$nic_arg',netdev='${network_name[$idx]}
        ;;
      "user")
        if [[ x${network_charid[$idx]} == x ]]; then
          ${network_charid[$idx]}='char'$idx
        fi
        if [[ x${network_path[$idx]} == x ]]; then
          echo "Need Path: "$idx
          exit 17
        fi
        nic_arg='-chardev socket,id='${network_charid[$idx]}'path='${network_path[$idx]}
        nic_arg=$nic_arg' '
        nic_arg=$nic_arg'-netdev type=vhost-user,id='${network_name[$idx]}'chardev='${network_charid[$idx]}',vhostforce'
        nic_arg=$nic_arg' '
        if [[ ${network_addr[$idx]} ]]; then
          create_macaddr
          nic_arg=$nic_arg'-device virtio-net-pci,mac='${macaddr}',netdev='${network_name[$idx]}',mrg_rxbuf=off'
        else
          nic_arg=$nic_arg'-device virtio-net-pci,netdev='${network_name[$idx]}',mrg_rxbuf=off'
        fi
        ;;
      "none")
        nic_arg='-net none'
        ;;
      *)
        echo "Unknown NIC type: "${network_type[$idx]}
        exit 18
        ;;
    esac
    net_args=$net_args' '$nic_arg

    ((idx=idx+1))
    
  done
}

##############################
#### Display
##############################
function create_display
{
  case "$display_type" in
    vnc)
      disp_args='-vga '$graphics_type' -vnc '$vnc_addr:$vnc_number
      ;;
    spice)
      disp_args='-vga qxl -spice addr='$spice_addr',port='$spice_port
      if [[ $spice_sasl == 'y' ]];then
        disp_args=$disp_args',sasl'
      else
        disp_args=$disp_args',disable-ticketing'
      fi
      if [[ $spice_tls == 'y' ]]; then
        if [[ x$spice_tls_port == x || x$ssl_SSLDIR == x ]]; then
          echo 'Need both TLS port and SSL cert dir specified.'
          exit 19
        fi
        disp_args=$disp_args',tls-port='$spice_tls_port',x509-dir='$ssl_SSLDIR
      fi
      ;;
    virtio)
      disp_args='-vga '$graphics_type' -display sdl,gl=on'
      ;;
    sdl)
      disp_args='-vga '$graphics_type' -sdl'
      ;;
    curses)
      disp_args='-curses'
      ;;
    none)
      disp_args='-display none'
      ;;
    off)
      disp_args='-nographic'
      ;;
    *)
      echo 'Illegal display: '$display_type
      exit 20
      ;;
  esac  
}

##############################
#### Keyboard
##############################
function create_kbd
{
  KBD_LIST="ar de-ch es fo fr-ca hu ja mk no pt-br sv da en-gb et fr fr-ch is lt nl pl ru th"
  KBD_LIST=$KBD_LIST"de en-us fi fr-be hr it lv nl-be pt sl tr"

  kbd_args=
  if [[ x$keyboard_lang != x ]]; then 
    for l in $KBD_LIST
    do
      if [[ $keyboard_lang = $l ]]; then
        kbd_args='-k '$keyboard_lang
        break
      fi
    done
  fi
}

##############################
#### RTC
##############################
function create_rtc
{
  rtc_args='-rtc'
  if [[ $clock_utctime == 'n' ]]; then
    rtc_args=$rtc_args' base=localtime'
  else
    rtc_args=$rtc_args' base=utc'
  fi
  if [[ $clock_sync_host == 'n' ]]; then
    rtc_args=$rtc_args',clock=vm'
  else
    rtc_args=$rtc_args',clock=host'
  fi
}

##############################
#### Create Run Directory
##############################
function create_rundir
{
    vmrundir=$system_rundir/$vm
    if [[ ! -d $vmrundir ]]; then
        $SUDO mkdir -p $vmrundir
        if [[ x$user_runas != x ]]; then
          $SUDO chown $user_runas:$user_runas $vmrundir
        fi
    fi
    chroot_dir=''
    if [[ x$user_chroot == 'y' ]]; then
      chroot_dir='-chroot '$vmrundir
    elif [[ -d $user_chroot ]]; then
      chroot_dir='-chroot '$user_chroot
    fi
}

##############################
#### Serial Port Socket
##############################
function get_serial
{
  serial_port=$system_rundir/$vm/serial.sock
}

##############################
#### Monitor Port Socket
##############################
function get_monitor
{
  monitor_port=$system_rundir/$vm/monitor.sock
}

##############################
#### PID file
##############################
function get_pid_file
{
  pid_file=$system_rundir/$vm/$vm.pid
}

##############################
#### Serial & Monitor
##############################
function create_console
{
  get_serial
  s_args='-serial unix:'$serial_port',server,nowait'
  get_monitor
  m_args='-monitor unix:'$monitor_port',server,nowait'
  console_args=$s_args' '$m_args
}

#############################
#### Build Command Line
#############################
function build_cmdline
{
  # io_mmu
  create_cpu
  check_numa
  create_rng
  create_mem
  create_bios
  create_tpm
  create_disk_drive
  create_floppy
  create_cdrom
  create_bootorder
  create_network_adaptor
  create_display
  create_kbd
  create_console
  create_rtc
  create_virtfs
  get_pid_file

  if [[ $system_qemu == 'kvm' ]]; then
    CMDLINE=$system_qemu
  else
    CMDLINE=$system_qemu' -enable-kvm'
  fi
  CMDLINE=$CMDLINE' -daemonize -runas '$user_runas' '$chroot_dir
  CMDLINE=$CMDLINE' -name '$vm
  CMDLINE=$CMDLINE' '$iommu_args' '$cpu_args' '$rng_args' '$mem_args
  CMDLINE=$CMDLINE' '$numa_args' '$boot_args' '$bios_args' '$disk_args
  CMDLINE=$CMDLINE' '$cd_args' '$fd_args' '$net_args' '$kbd_args
  CMDLINE=$CMDLINE' '$disp_args' '$console_args' '$rtc_args
  CMDLINE=$CMDLINE' -pidfile '$pid_file

  if [[ x$misc_args != x ]]; then
    CMDLINE=$CMDLINE' '$misc_args
  fi
}

########################################
### Read configuratio file
########################################
function read_conf_file
{
  cmds=$(awk -f - $1 <<EOAS
  
  BEGIN {
    DISKS    = -1;
    NICS     = -1;
    CSECTION = "";
  }
  
  /^[ \\ta-zA-Z0-9_-+!@$%^&\\/.:]+/ {
    pos   = index(\$0, "=");
    if (pos > 0)
    {
          left  = substr(\$0, 1, pos - 1);
          right = substr(\$0, pos + 1, length(\$0) - pos);
          gsub("^[ \\t]+" ,"", left);
          gsub("[ \\t]+$" ,"", left);
          gsub("^[ \\t]+" ,"", right);
          gsub("[ \\t]+$" ,"", right);
          left = tolower(left);
          if (match(CSECTION, "disk") > 0)
          {
            left = sprintf("%s[%d]", left, DISKS);
          }
          if (match(CSECTION, "network") > 0)
          {
            left = sprintf("%s[%d]", left, NICS);
          }
          printf ("%s_%s=%s\n", CSECTION, left, right);
    }
  }
  
/^[ \\t]*\\[[a-zA-Z0-9_-+!@$%^&\\/.:]+/ {
  gsub("^[ \\t]+" ,"", \$1);
  gsub("[ \\t]+$" ,"", \$1);
  gsub("^\\[" ,"", \$1);
  gsub("\\]$" ,"", \$1);
  CSECTION = \$1;
  if (match(CSECTION,"disk") > 0)
  {     
        DISKS = DISKS + 1;
  }
  if (match(CSECTION, "network") > 0)
  {     
        NICS = NICS + 1;
  }
}
EOAS
)
  for v in $cmds;
  do
    eval $v
  done
}

########################################
### Read configuration
########################################
function read_conf
{
  set_default_values

  def_conf=$SYSDIR/vmmaestro.conf

  if [ ! -f $def_conf ]; then
    echo You must place vmmaestro.conf in $SYSDIR
    exit 21
  fi
  read_conf_file $def_conf
  if [[ x$system_sasl_conf_path != x ]]; then
    export SASL_CONF_PATH=$system_sasl_conf_path
  fi

  vm_conf=$SYSDIR/$vm.conf

  if [ ! -f $vm_conf ]; then
    echo You must place $vm.conf in $SYSDIR
    exit 22
  fi
  read_conf_file $vm_conf
}

########################################
### Destroy configuration
########################################
function del_conf
{
  unset vm
  unset cpu_cores
  unset cpu_threads
  unset cpu_sockets
  unset cpu_iswinguest
  unset network_type
  unset network_addr
  unset network_name
  unset network_model
  unset network_vhost
  unset network_bridge
  unset network_if
  unset network_ifup
  unset network_ifdown
  unset vg_name
  unset disk_lv
  unset disk_if
  unset disk_fmt
  unset disk_dp
  unset disk_aio
  unset cdrom_iso
  unset cdrom_if
  unset keyboard_lang
  unset floppy_drive1
  unset floppy_drive2
  unset display_type
  unset spice_port
  unset spice_tls_port
  unset system_SASL_CONF_PATH
  unset system_SSLDIR
}

########################################
### Is running process
########################################
function proc_check
{
  get_pid_file
  if [[ ! -f $pid_file ]]; then
  	return 1
  fi
  $SUDO kill -0 `$SUDO cat $pid_file` > /dev/null 2>&1
  return $?
}

########################################
### start vm
########################################
function start_vm
{
  create_rundir

  build_cmdline
  $E $SUDO $CMDLINE

}

########################################
### shutdown vm
########################################
function shutdown_vm
{
  get_monitor
  echo system_powerdown | $SUDO socat - UNIX-CONNECT:$monitor_port
  delay=0
  proc_check
  while [[ ! $? && $delay < $boot_qemu_delay ]];
  do
    ((delay=delay+1))
    sleep 1
    proc_check
  done

  if [[ $boot_qemu_delay == $delay ]]; then
      echo Failed to shutdown $vm
      exit 23
  fi
}

########################################
### stop vm
########################################
function stop_vm
{
  get_monitor
  echo quit | $SUDO socat - UNIX-CONNECT:$monitor_port
  delay=0
  proc_check
  while [[ ! $? && $delay < $boot_qemu_delay ]];
  do
    ((delay=delay+1))
    sleep 1
    proc_check
  done

  if [[ $boot_qemu_delay == $delay ]]; then
      echo Failed to stop $vm
      exit 24
  fi
}

########################################
### stauts vm
########################################
function status_vm
{
  echo -n $vm" "
  proc_check
  if [[ $? -ne 0 ]]; then
    echo is stopped.
    return 1
  else
    echo is running.
    return 0
  fi
}

#############################
#### Show CPU info
#############################
function show_cpus
{
  check_cpu $cpu_model
  if [[ ! $? ]]; then
    model="Illegal CPU"
  else
    model=$cpu_model
  fi

  printf "CPU: Model=%s, Units=%d" $model $cpu_units

  if [[ x$cpu_cores != x ]]; then
    printf ",Cores=%d" $cpu_cores
  fi
  if [[ x$cpu_threads != x ]]; then
    printf ",Threads=%d" $cpu_threads
  fi
  if [[ x$cpu_sockets != x ]]; then
    printf ",Sockets=%d" $cpu_sockets
  fi
  if [[ $cpu_iswinguest != 0 ]]; then
    printf ", Windows Mode"
  fi
  echo
}

#############################
#### Show Memory info
#############################
function show_mem
{
  printf "MEM: %d MB, auto=" $memory_vmem
  if [[ $memory_auto == 'y' ]]; then
    printf "\e[36;1menabled\e[0m"
  else
    printf "\e[31;1mdisabled\e[0m"
  fi
  if [[ $memory_huge == 'y' ]]; then
    printf ",Huge"
    if [[ $memory_share == 'y' ]]; then
      if  [[ ! $memory_sharemem ]]; then
        memory_sharemem=$memory_vmem
      fi
      printf ",Shared=%d" $memory_sharemem
    fi
    if [[ $memory_prealloc == 'y' ]]; then
      printf ",Pre-Alloc"
    fi
  fi
  if [[ $numa_is_numa == 'y' ]]; then
    printf "Numa=enabled"
  fi
  echo
}

#############################
#### Show IOMMU
#############################
function show_iommu
{
  if [[ ! -z $iommu_vendor ]]; then
    printf "IOMMU: %s\n" $iommu_vendor
  fi
}

#############################
#### Show RNG
#############################
function show_rng
{
  if [[ $rng_enable == 'y' ]]; then
    printf "RNG: enabled\n" 
  fi
}

##############################
#### Show BIOS
##############################
function show_bios
{
  if [[ x$bios_file != x ]]; then
    if [[ $bios_type = 'uefi' ]]; then
      printf "UEFI: file=%s" $bios_file
    else
      printf "BIOS: file=%s" $bios_file
      echo
    fi
  fi
  case  "$bios_type" in
    'uefi')
      if [[ x$bios_nvram != x ]]; then
        printf ", nvram=%s" $bios_nvram
      fi
      echo
      ;;
    '0')
      printf "BIOS: type=0"
      if [[ x$bios_vendor != x ]]; then
        printf ",vender=%s" $bios_vendor
      fi
      if [[ x$bios_version != x ]]; then
        printf ",version=%s" $bios_version
      fi
      if [[ x$bios_date != x ]]; then
        printf ",date=%s" $bios_date
      fi
      if [[ x$bios_release != x ]]; then
        printf ",release=%s" $bios_release
      fi
      echo
      ;;
    '1')
      printf "BIOS: type=1"
      if [[ x$bios_manufacturer != x ]]; then
        printf ",manufacturer=%s" $bios_manufacturer
      fi
      if [[ x$bios_product != x ]]; then
        printf ",product=%d" $bios_product
      fi
      if [[ x$bios_version != x ]]; then
        printf ",version=%s" $bios_version
      fi
      if [[ x$bios_serial != x ]]; then
        printf ",serial=%s" $bios_serial
      fi
      if [[ x$bios_uuid != x ]]; then
        printf ",uuid=%s" $bios_uuid
      fi
      if [[ x$bios_sku != x ]]; then
        printf ",sku=%s" $bios_sku
      fi
      if [[ x$bios_family != x ]]; then
        printf ",family=%s" $bios_family
      fi
      echo
      ;;
    '2')
      printf "BIOS: type=2"
      if [[ x$bios_manufacturer != x ]]; then
        printf ",manufacturer=%s" $bios_manufacturer
      fi
      if [[ x$bios_product != x ]]; then
        printf ",product=%s" $bios_product
      fi
      if [[ x$bios_version != x ]]; then
        printf ",version=%s" $bios_version
      fi
      if [[ x$bios_serial != x ]]; then
        printf ",serial=%s" $bios_serial
      fi
      if [[ x$bios_asset != x ]]; then
        printf ",asset=%s" $bios_asset
      fi
      if [[ x$bios_location != x ]]; then
        printf ",location=%s" $bios_location
      fi
      if [[ x$bios_family != x ]]; then
        printf ",family=%s" $bios_family
      fi
      echo
      ;;
    '3')
      printf "BIOS: type=3"
      if [[ x$bios_manufacturer != x ]]; then
        printf ",manufacturer=%s" $bios_manufacturer
      fi
      if [[ x$bios_version != x ]]; then
        printf ",version=%s" $bios_version
      fi
      if [[ x$bios_serial != x ]]; then
        printf ",serial=%s" $bios_serial
      fi
      if [[ x$bios_asset != x ]]; then
        printf ",asset=%s" $bios_asset
      fi
      if [[ x$bios_sku != x ]]; then
        printf ",sku=%s" $bios_sku
      fi
      echo
      ;;
    '4')
      printf "BIOS: type=4"
      if [[ x$bios_sock != x ]]; then
        printf ",sock_pfx=%s" $bios_sock
      fi
      if [[ x$bios_manufacturer != x ]]; then
        printf ",manufacturer=%s" $bios_manufacturer
      fi
      if [[ x$bios_version != x ]]; then
        printf ",version=%s" $bios_version
      fi
      if [[ x$bios_serial != x ]]; then
        printf ",serial=%s" $bios_serial
      fi
      if [[ x$bios_asset != x ]]; then
        printf ",asset=%s" $bios_asset
      fi
      if [[ x$bios_part != x ]]; then
        printf ",part=%s" $bios_part
      fi
      echo
      ;;
    '17')
      printf "BIOS: type=17"
      if [[ x$bios_loc_pfx != x ]]; then
        printf ",loc_pfx=%s" $bios_loc_pfx
      fi
      if [[ x$bios_bank != x ]]; then
        printf ",bank=%s" $bios_bank
      fi
      if [[ x$bios_manufacturer != x ]]; then
        printf ",manufacturer=%s" $bios_manufacturer
      fi
      if [[ x$bios_serial != x ]]; then
        printf ",serial=%s" $bios_serial
      fi
      if [[ x$bios_asset != x ]]; then
        printf ",asset=%s" $bios_asset
      fi
      if [[ x$bios_part != x ]]; then
        printf ",part=%s" $bios_part
      fi
      if [[ x$bios_speed != x ]]; then
        printf ",speed=%s" $bios_speed
      fi
      echo
      ;;
    '*')
      ;;
  esac
}

##############################
### show TPM device
##############################
function show_tpm
{
  if [[ x"${tpm_enable}" == x"true" ]] || [[ x"${tpm_enable}" == x"yes" ]]; then
    printf "TPM: enabled. type=%s\n" ${tpm_type}
    if [[ "${tpm_type}" = "passthrough" ]]; then
      printf "     id=%s,path=%s" ${tpm_id} ${tpm_dev}
    elif [[ "${tpm_type}" = "emulator" ]]; then
      printf "     id=%s,char_id=%s,char_path=%s" ${tpm_id} ${tpm_char_id} ${tpm_char_path}
    else
      printf "     \e[31;1mIllegal TPM type: %s\e[0m" ${tpm_type}
    fi
  else
    printf "TPM: disabled\n"
  fi
}

##############################
#### Show Disks
##############################
function show_disks
{
  idx=0
  while [[ x${disk_lv[$idx]} != x ]];
  do
    if [[ x$vg_name != x ]]; then
        printf "DISK %d: /dev/%s/%s" $idx $vg_name ${disk_lv[$idx]}
        disk_drive=/dev/$vg_name/${disk_lv[$idx]}
        if [[ ! -b $disk_drive ]]; then
            printf "\e[31;1mNot Found\e[0m."
        fi
    else
        printf "DISK %d: %s" $idx ${disk_lv[$idx]}
        disk_drive=${disk_lv[$idx]}
        if [[ ! -f $disk_drive ]]; then
            printf "\e[31;1mNot Found\e[0m."
        fi
    fi
    if [[ x${disk_if[$idx]} == x ]]; then
      disk_if[$idx]=$DEF_DISKIF
    fi
    color="0"
    case "${disk_if[$idx]}" in
      "ide")      ;;
      "scsi")     ;;
      "virtio")   ;;
      "virtio-scsi") ;;
      *)
        color="31;1"
        ${disk_if[$idx]}="Not supported"
        ;;
    esac
    printf ",if=\e[%sm%s\e[0m" $color ${disk_if[$idx]}
    if [[ x${disk_aio[$idx]} == x ]]; then
      disk_aio[$idx]='native'
    fi
    color="0"
    case "${disk_aio[$idx]}" in
      "native")   ;;
      "threads")  ;;
      *)
        color="31;1"
        disk_aio[$idx]="Not supported"
        ;;
    esac
    printf ",aio=\e[%sm%s\e[0m" $color "${disk_aio[$idx]}"
    if [[ x${disk_fmt[$idx]} != x ]]; then
      printf ",format=%s" ${disk_fmt[$idx]}
    fi
    echo
    ((idx=idx+1))
  done
}

##############################
#### Show CD-ROM
##############################
function show_cdrom
{
  color="0"
  case "$cdrom_if" in
    "ide")    ;;
    "scsi")   ;;
     *)
       color="31;1"
       $cdrom_if="Not supported"
  esac
  if [[ x$cdrom_iso != x ]]; then
    printf "CDROM: if=\e[%sm%s\e[0m,iso=%s" $color "$cdrom_if" $cdrom_iso
    if [[ ! -f $cdrom_iso ]]; then
        printf " \e[31;1mNot found\e[0m"
    fi
    echo
  fi
}

##############################
### Show Boot order
##############################
function show_boot
{
  if [[ x$boot_order != x ]]; then
    printf "BOOT: %s" $boot_order
    if [[ x$bios_menu == 'y' ]]; then
      printf ",menu=on"
    fi
    echo
  else
    if [[ x$bios_menu == 'y' ]]; then
      boot_args="-boot menu=on"
      echo
    fi
  fi
}

##############################
#### Show Network
##############################
function show_network
{
  idx=0
  while [[ x${network_type[$idx]} != x ]];
  do

    color="0"
    if [[ x${network_name[$idx]} == x ]]; then
      color="31;1"
      network_name[$idx]="None"
    fi
    if [[ x${network_model[$idx]} == x ]]; then
      network_model[$idx]=$DEF_NIC
    fi
    check_nic ${network_model[$idx]}
    color2="0"
    if [[ ! $? ]]; then
      color2="31;1"
      network_model[$idx]="Unsupported" 
    fi

    printf "NET %d: Model=\e[%sm%s\e[0m,Name=\e[%sm%s\e[0m" $idx  $color2 ${network_model[$idx]} $color ${network_name[$idx]}
    case "${network_type[$idx]}" in
      "bridge")
        printf ",type=%s" ${network_type[$idx]}
        if [[ ${network_vlan[$idx]} ]]; then
          printf ",vlan=%s" $network_vlan
        fi
        if [[ ${network_addr[$idx]} ]]; then
          create_macaddr
          printf ",mac=%s" ${macaddr}
        fi
        ;;
      "tap")
        printf ",type=%s,id=%s" ${network_type[$idx]} ${network_name[$idx]}
        if [[ x${network_vhost[$idx]} != x && ${network_vhost[$idx]} == 'y' ]]; then
          printf ",vhost=on"
          network_model[$idx]=$DEF_NIC
        fi
        color="0"
        if [[ x${network_if[$idx]} == x ]]; then
          color="31;1"
          network_if[$idx]="None"
        fi
        printf ",ifname=\e[%sm%s\e[0m\n" $color ${network_if[$idx]}
        color="0"
        if [[ x${network_ifup[$idx]} == x ]]; then
          color="31;1"
          network_ifup[$idx]="None"
        else
          printf "\tscript=\e[%sm%s\e[0m" $color ${network_ifup[$idx]}
        fi
        color="0"
        if [[ x${network_ifdown[$idx]} == x ]]; then
          color="31;1"
          network_ifdown[$idx]="None"
        fi
        printf ",downscript=\e[%sm%s\e[0m" $color ${network_ifdown[$idx]}
        if [[ ${network_vlan[$idx]} ]]; then
          printf ",vlan=%s" $network_vlan
        fi
        if [[ ${network_addr[$idx]} ]]; then
          create_macaddr
          printf ",mac=%s" ${macaddr}
        fi
        ;;
      "user")
        printf ",type=%s" ${network_type[$idx]}
        if [[ x${network_charid[$idx]} == x ]]; then
          ${network_charid[$idx]}='char'$idx
        fi
        color="0"
        if [[ x${network_path[$idx]} == x ]]; then
          color="31;1"
          network_path[$idx]="None"
        fi
        printf ",id=%s,name=%s,path=\e[%sm%s\e[0m" ${network_charid[$idx]} ${network_name[$idx]} $color ${network_path[$idx]}
        if [[ ${network_addr[$idx]} ]]; then
          create_macaddr
          printf ",mac=%s" ${macaddr}
        fi
        ;;
      "none")
        printf ",type=%s" ${network_type[$idx]}
        ;;
      *)
        printf ",type=\e[31;1mInvalid Type\e[0m"
        ;;
    esac
    echo
    ((idx=idx+1))
    
  done
}

##############################
#### Show Display
##############################
function show_display
{
  case "$display_type" in
    vnc)
      printf "VNC: "$vnc_addr:$vnc_number
      ;;
    spice)
      printf "SPiCE addr=%s,port=%s"  $spice_addr $spice_port
      if [[ $spice_sasl == 'y' ]];then
        printf ",sasl"
      fi
      if [[ $spice_tls == 'y' ]]; then
        color="0"
        if [[ x$spice_tls_port == x ]]; then
          color="31;1"
          spice_tls_port="None"
        fi
        color2="0"
        if [[ x$ssl_SSLDIR == x ]]; then
          color2="31;1"
          ssl_SSLDIR="\e[31;1mNone\e[0m"
        fi
        printf ",tls-port=\e[%sm%s\e[0m,x509-dir=\e[%sm%s\e[0m" $color $spice_tls_port $color2 $ssl_SSLDIR
      fi
      ;;
    virtio)
      printf "VirtIO: type=%s" $graphics_type
      ;;
    sdl)
      printf "SDL: type=%s" $graphics_type
      ;;
    curses)
      printf "Curses"
      ;;
    none)
      printf "NONE"
      ;;
    off)
      printf "OFF"
      ;;
    *)
      printf "\e[31;1mInvalid Display\e[0m"
      ;;
  esac  
  echo
}

##############################
#### Show Keyboard
##############################
function show_kbd
{

  KBD_LIST="ar de-ch es fo fr-ca hu ja mk no pt-br sv da en-gb et fr fr-ch is lt nl pl ru th"
  KBD_LIST=$KBD_LIST"de en-us fi fr-be hr it lv nl-be pt sl tr"

  flag=0
  if [[ x$keyboard_lang != x ]]; then 
    printf "KBD: %s" $keyboard_lang
    for l in $KBD_LIST
    do
      if [[ $keyboard_lang = $l ]]; then
        flag=1
        break
      fi
    done
    if [[ ! $flag ]]; then
      printf "\e[31;1mInvalid KBD\e[0m"
    fi
    echo
  fi
}

##############################
#### Show RTC
##############################
function show_rtc
{
  printf "RTC: "
  if [[ $clock_utctime == 'n' ]]; then
    printf "LocalTime"
  else
    printf "UTC"
  fi
  if [[ $clock_sync_host == 'n' ]]; then
    printf ",Not Sync"
  else
    printf ",Sync"
  fi
  echo
}

##############################
#### Show chroot
##############################
function show_rundir
{
    vmrundir=$system_rundir/$vm
    printf "RUNDIR: %s\n" $vmrundir
    chroot_dir=''
    if [[ -d $user_chroot ]]; then
      printf "CHROOT: %s\n" $user_chroot
    fi
}

##############################
#### Show Serial Port Socket
##############################
function show_serial
{
  serial_port=$system_rundir/$vm/serial.sock
  printf "SERIAL: %s\n" $serial_port
}

##############################
#### Show Monitor Port Socket
##############################
function show_monitor
{
  monitor_port=$system_rundir/$vm/monitor.sock
  printf "MONITOR: %s\n" $monitor_port
}

##############################
#### Show PID file
##############################
function show_pid_file
{
  pid_file=$system_rundir/$vm/$vm.pid
  printf "PID: %s\n" $pid_file
}

##############################
### Show VirtFS
##############################
function show_virtfs
{
  if [[ ! -z $virtfs_driver ]]; then
    color="0"
    case "$virtfs_driver" in
      "local")	;;
      "handle")	;;
      "proxy")	;;
      *)
        color="31;1"
        virtfs_driver="Illegal Driver"
      ;;
    esac
    printf "VirtFS: driver=\e[%sm%s\e[0m" $color "$virtfs_driver"
    if [[ x$virtfs_id == x ]]; then
      virtfs_id=$vm
    fi
    printf ",id=%s" $virtfs_id
    color="0"
    if [[ ! -d $virtfs_path ]]; then
      color="31;1"
      virtfs_path="Not Found"
    fi
    printf ",path=\e[%sm%s\e[0m" $color "$virtfs_path"
    if [[ x$virtfs_security != x ]] ; then
      color="0"
      case "$virtfs_security" in
        "passthrough")	;;
        "mapped-xattr")	;;
        "mapped-file")	;;
        "none")	;;
        *)
          color="31;1"
          virtfs_security="Error"
          ;;
      esac
      printf ",security_model=\e[%sm%s\e[0m" $color  $virtfs_security
      if [[ $virtfs_writeout == 'y' ]]; then
        printf ",writeout=immediate"
      fi
      if [[ $virtfs_readonly == 'y' ]]; then
        printf ",readonly"
      fi
      if [[ $virtfs_driver == "proxy" ]]; then
        printf ",socket=%s" $system_rundir/$vm/virtfs.sock
        printf ",sock_fd"
      fi
    fi
    echo
  fi
}

#############################
#### Show Conf
#############################
function show_conf
{
  show_cpus 
  show_iommu
  show_rng
  show_mem
  show_bios
  show_tpm
  show_disks
  show_cdrom
  show_boot
  show_network
  show_display
  show_kbd
  show_rtc
  show_virtfs
  show_rundir
  show_serial
  show_monitor
  show_pid_file
}

########################################
### list vm
########################################
function list_vm
{
  proc_check
  if [[ $? -ne 0 ]]; then
    color=31
    stat="Stopped"
    res=1
  else
    color=36
    stat="Running"
    res=0
  fi
  printf "%s:\t\e[%d;1m%s\e[0m.\n" $vm $color $stat
  show_conf
  echo

  return $res
}

########################################
### list all vm
########################################
function list_all
{
  if [[ ! -z "$1" && "$1" != "-s" && "$1" != "--status" ]]; then
      echo "Unknown option: "$1
      exit 27
  fi
  opt=$1
  ls $SYSDIR/*.conf | while read conf
  do
    vm=$(basename $conf .conf)
    if [[ "$vm" != "vmmaestro" && -f "$conf" ]]; then
      read_conf
      if [[ ! -z $opt ]]; then
        status_vm
      else
        list_vm
      fi
      del_conf
    fi
  done
}

########################################
### Connect to console
########################################
function connect_to_console
{
  clear
  get_serial
  echo For reasons unknown, ^O is the panic button.
  $SUDO socat -,raw,echo=0,escape=0x0f UNIX-CONNECT:$serial_port 
}

########################################
### Connect to monitor
########################################
function connect_to_monitor
{
  clear
  get_monitor
  echo For reasons unknown, ^O is the panic button.
  $SUDO socat -,raw,echo=0,escape=0x0f UNIX-CONNECT:$monitor_port
}

########################################
### main
########################################

if [[ $use_sudo == 'y' ]]; then
  SUDO='sudo'
elif [[ $use_sudo == 'd' ]]; then
  SUDO='doas'
else
  SUDO=
fi

cmd=$1
shift

if [[ "$cmd" == "list" ]]; then

  list_all $1

else

  res=0

  while [[ "$1" ]]; do
    vm=$1
    read_conf
    case "$cmd" in
      console|serial|serial0)
        connect_to_console
        ;;
      monitor|kvm|qemu)
        connect_to_monitor
        ;;
      consolestart|cstart)
        start_vm
        connect_to_console
        break
        ;;
      start)
        start_vm
        ;;
      stop)
        stop_vm
        ;;
      shutdown)
        shutdown_vm
        ;;
      restart)
        shutdown_vm
        start_vm
        ;;
      kill)
        get_pid_file
        $SUDO kill -KILL `$SUDO cat $pid_file`
        ;;
      status)
        status_vm
        res=$(( $res + $? ))
        ;;
      show)
        list_vm
        res=$(( $res + $? ))
        ;;
      *)
        echo "Unknown command: "$cmd. >&2
        exit 26
        ;;
    esac
    del_conf
    shift
  done

fi

exit $res
